--------------------------------------------------------
-- Archivo creado  - miércoles-marzo-31-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_USUARIOS
--------------------------------------------------------

   CREATE SEQUENCE  "EVALUACION_M2"."SEQ_USUARIOS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 15 CACHE 5 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table PROFESIONAL
--------------------------------------------------------

  CREATE TABLE "EVALUACION_M2"."PROFESIONAL" 
   (	"PROFESIONAL_IDUSUARIO" NUMBER(9,0), 
	"TELEFONO" NUMBER(12,0), 
	"TITULO" VARCHAR2(50 BYTE), 
	"PROYECTO" VARCHAR2(70 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ADMINISTRATIVO
--------------------------------------------------------

  CREATE TABLE "EVALUACION_M2"."ADMINISTRATIVO" 
   (	"ADMINISTRATIVO_IDUSUARIO" NUMBER(9,0), 
	"CORREO" VARCHAR2(25 BYTE), 
	"AREA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIOS
--------------------------------------------------------

  CREATE TABLE "EVALUACION_M2"."USUARIOS" 
   (	"IDUSUARIO" NUMBER(9,0), 
	"NOMBREUSER" VARCHAR2(100 BYTE), 
	"APELLIDOUSER" VARCHAR2(100 BYTE), 
	"FECHANACIMIENTO" DATE, 
	"RUN" NUMBER(9,0), 
	"TIPO_USUARIO" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CAPACITACION
--------------------------------------------------------

  CREATE TABLE "EVALUACION_M2"."CAPACITACION" 
   (	"IDCAPACITACION" NUMBER(9,0), 
	"CAPFECHA" DATE, 
	"CAPHORA" DATE, 
	"CAPLUGAR" VARCHAR2(100 BYTE), 
	"CAPDURACION" NUMBER(4,0), 
	"CLIENTE_RUTCLIENTE" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "EVALUACION_M2"."CLIENTE" 
   (	"RUTCLIENTE" NUMBER(9,0), 
	"CLINOMBRES" VARCHAR2(30 BYTE), 
	"CLIAPELLIDOS" VARCHAR2(50 BYTE), 
	"CLITELEFONO" VARCHAR2(20 BYTE), 
	"CLIAFP" VARCHAR2(30 BYTE), 
	"CLISISTEMASALUD" NUMBER(2,0), 
	"CLIDIRECCION" VARCHAR2(100 BYTE), 
	"CLICOMUNA" VARCHAR2(50 BYTE), 
	"CLIEDAD" NUMBER(3,0), 
	"CLIENTE_IDUSUARIO" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROFESIONAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVALUACION_M2"."PROFESIONAL_PK" ON "EVALUACION_M2"."PROFESIONAL" ("PROFESIONAL_IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ADMINISTRATIVO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVALUACION_M2"."ADMINISTRATIVO_PK" ON "EVALUACION_M2"."ADMINISTRATIVO" ("ADMINISTRATIVO_IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USUARIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVALUACION_M2"."USUARIOS_PK" ON "EVALUACION_M2"."USUARIOS" ("IDUSUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CAPACITACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVALUACION_M2"."CAPACITACION_PK" ON "EVALUACION_M2"."CAPACITACION" ("IDCAPACITACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVALUACION_M2"."CLIENTE_PK" ON "EVALUACION_M2"."CLIENTE" ("RUTCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger TRIG_USUARIOS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EVALUACION_M2"."TRIG_USUARIOS" 
BEFORE INSERT ON USUARIOS 
FOR EACH ROW
 WHEN (NEW.IDUSUARIO IS NULL) BEGIN
SELECT SEQ_USUARIOS.NEXTVAL
INTO :NEW.IDUSUARIO
FROM DUAL;
END;
/
ALTER TRIGGER "EVALUACION_M2"."TRIG_USUARIOS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_USUARIOS
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EVALUACION_M2"."TRIG_USUARIOS" 
BEFORE INSERT ON USUARIOS 
FOR EACH ROW
 WHEN (NEW.IDUSUARIO IS NULL) BEGIN
SELECT SEQ_USUARIOS.NEXTVAL
INTO :NEW.IDUSUARIO
FROM DUAL;
END;
/
ALTER TRIGGER "EVALUACION_M2"."TRIG_USUARIOS" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIG_CAP
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "EVALUACION_M2"."TRIG_CAP" 
BEFORE INSERT ON CAPACITACION
FOR EACH ROW
 WHEN (NEW.IDCAPACITACION IS NULL) BEGIN
SELECT SEQ_CAP.NEXTVAL
INTO :NEW.IDCAPACITACION
FROM DUAL;
END;
/
ALTER TRIGGER "EVALUACION_M2"."TRIG_CAP" ENABLE;
--------------------------------------------------------
--  Constraints for Table PROFESIONAL
--------------------------------------------------------

  ALTER TABLE "EVALUACION_M2"."PROFESIONAL" ADD CONSTRAINT "PROFESIONAL_PK" PRIMARY KEY ("PROFESIONAL_IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EVALUACION_M2"."PROFESIONAL" MODIFY ("PROYECTO" NOT NULL ENABLE);
  ALTER TABLE "EVALUACION_M2"."PROFESIONAL" MODIFY ("TITULO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMINISTRATIVO
--------------------------------------------------------

  ALTER TABLE "EVALUACION_M2"."ADMINISTRATIVO" ADD CONSTRAINT "ADMINISTRATIVO_PK" PRIMARY KEY ("ADMINISTRATIVO_IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EVALUACION_M2"."ADMINISTRATIVO" MODIFY ("AREA" NOT NULL ENABLE);
  ALTER TABLE "EVALUACION_M2"."ADMINISTRATIVO" MODIFY ("CORREO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USUARIOS
--------------------------------------------------------

  ALTER TABLE "EVALUACION_M2"."USUARIOS" ADD CONSTRAINT "USUARIOS_PK" PRIMARY KEY ("IDUSUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EVALUACION_M2"."USUARIOS" MODIFY ("RUN" NOT NULL ENABLE);
  ALTER TABLE "EVALUACION_M2"."USUARIOS" MODIFY ("APELLIDOUSER" NOT NULL ENABLE);
  ALTER TABLE "EVALUACION_M2"."USUARIOS" MODIFY ("NOMBREUSER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAPACITACION
--------------------------------------------------------

  ALTER TABLE "EVALUACION_M2"."CAPACITACION" ADD CONSTRAINT "CAPACITACION_PK" PRIMARY KEY ("IDCAPACITACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EVALUACION_M2"."CAPACITACION" MODIFY ("CLIENTE_RUTCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "EVALUACION_M2"."CAPACITACION" MODIFY ("CAPLUGAR" NOT NULL ENABLE);
  ALTER TABLE "EVALUACION_M2"."CAPACITACION" MODIFY ("CAPFECHA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "EVALUACION_M2"."CLIENTE" MODIFY ("CLIENTE_IDUSUARIO" NOT NULL ENABLE);
  ALTER TABLE "EVALUACION_M2"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("RUTCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "EVALUACION_M2"."CLIENTE" MODIFY ("CLIEDAD" NOT NULL ENABLE);
  ALTER TABLE "EVALUACION_M2"."CLIENTE" MODIFY ("CLICOMUNA" NOT NULL ENABLE);
  ALTER TABLE "EVALUACION_M2"."CLIENTE" MODIFY ("CLIDIRECCION" NOT NULL ENABLE);
  ALTER TABLE "EVALUACION_M2"."CLIENTE" MODIFY ("CLITELEFONO" NOT NULL ENABLE);
  ALTER TABLE "EVALUACION_M2"."CLIENTE" MODIFY ("CLIAPELLIDOS" NOT NULL ENABLE);
  ALTER TABLE "EVALUACION_M2"."CLIENTE" MODIFY ("CLINOMBRES" NOT NULL ENABLE);
  ALTER TABLE "EVALUACION_M2"."CLIENTE" MODIFY ("RUTCLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table PROFESIONAL
--------------------------------------------------------

  ALTER TABLE "EVALUACION_M2"."PROFESIONAL" ADD CONSTRAINT "FK_PROFESIONAL" FOREIGN KEY ("PROFESIONAL_IDUSUARIO")
	  REFERENCES "EVALUACION_M2"."USUARIOS" ("IDUSUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADMINISTRATIVO
--------------------------------------------------------

  ALTER TABLE "EVALUACION_M2"."ADMINISTRATIVO" ADD CONSTRAINT "ADMINISTRATIVO_FK" FOREIGN KEY ("ADMINISTRATIVO_IDUSUARIO")
	  REFERENCES "EVALUACION_M2"."USUARIOS" ("IDUSUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CAPACITACION
--------------------------------------------------------

  ALTER TABLE "EVALUACION_M2"."CAPACITACION" ADD CONSTRAINT "CAPACITACION_CLIENTE_FK" FOREIGN KEY ("CLIENTE_RUTCLIENTE")
	  REFERENCES "EVALUACION_M2"."CLIENTE" ("RUTCLIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "EVALUACION_M2"."CLIENTE" ADD CONSTRAINT "FK_CLIENTE" FOREIGN KEY ("CLIENTE_IDUSUARIO")
	  REFERENCES "EVALUACION_M2"."USUARIOS" ("IDUSUARIO") ENABLE;
